
package GUI;

import javax.media.j3d.Canvas3D;
import Model.Universo;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author fvelasco
 */
public class ControlWindow extends JFrame {
  private final Universo universe;

  public ControlWindow(Canvas3D canvas, Universo anUniverse) {
    super();
    universe = anUniverse;
    initComponents();
    setLocation (920, 100);
    addWindowListener(new WindowAdapter() {
      @Override
      public void windowClosing(WindowEvent e) {
        closeApp(0);
      }
    });
   
    Container contentPane = this.getContentPane();
    contentPane.setLayout(new BorderLayout());
    contentPane.add(canvas, BorderLayout.CENTER);
    pack();
        
    // Inicializamos la 2º ventana
    Visualization visualization = new Visualization (this, false, canvas);
    visualization.setVisible(true);

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primitiveGroup = new javax.swing.ButtonGroup();
        appearanceGroup = new javax.swing.ButtonGroup();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Control");
        setMinimumSize(new java.awt.Dimension(300, 345));
        getContentPane().setLayout(new java.awt.GridLayout(5, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  public void showWindow () {
    setVisible (true);
  }

  void closeApp (int code) {
    universe.closeApp(code);
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup appearanceGroup;
    private javax.swing.ButtonGroup primitiveGroup;
    // End of variables declaration//GEN-END:variables
}
